version: '3.8'

services:
  my_postgres_db:
    image: postgres
    environment:
      POSTGRES_USER: axl_backstage_user
      POSTGRES_PASSWORD: axl_backstage_pass
      POSTGRES_DB: axl_backstage_plugins
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5437:5432'

  my_pfadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5051:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./.devcontainer/pgadmin4/servers.json:/pgadmin4/servers.json
    depends_on:
      - my_postgres_db

  my_devcontainer:
    # image: mcr.microsoft.com/vscode/devcontainers/typescript-node:18
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    command: /bin/sh -c "chown node:root /workspace/node_modules /workspace/packages/app/node_modules /workspace/packages/backend/node_modules && while sleep 1000; do :; done"
    volumes:
      - .:/workspace
      - main_node_modules:/workspace/node_modules
      - app_node_modules:/workspace/packages/app/node_modules
      - backend_node_modules:/workspace/packages/backend/node_modules
    environment:
      APP_DATABASE_HOST: my_postgres_db
      APP_DATABASE_USER: axl_backstage_user
      APP_DATABASE_PASSWORD: axl_backstage_pass
      APP_DATABASE_PORT: 5432
      APP_DATABASE_DBNAME: axl_backstage_plugins
    env_file:
      - .devcontainer/devcontainer.env

  my_redis:
    image: redis
    ports:
      - '6377:6379'

volumes:
  main_node_modules:
  app_node_modules:
  backend_node_modules:
  pg_data:
  pgadmin_data:
